services:
  postgres:
    image: test/db
    container_name: db
    environment:
      - "POSTGRES_DB=testDRS"
      - "POSTGRES_USERNAME=postgres"
      - "POSTGRES_PASSWORD=20040601"
    ports:
      - "5432:5432"
  app:
    image: test/app
    container_name: app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
     image: test/api
     container_name: api
     ports:
      - 8080:8080
networks:
      mynet:
        driver: bridge
    